//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org_maint_services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetHistory
    {
        public int BudgetHistoryId { get; set; }
        public decimal Amount { get; set; }
        public string DebitCredit { get; set; }
        public System.DateTime Date { get; set; }
    }
}
