//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org_maint_services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contributor
    {
        public int ContributorID { get; set; }
        public string ContributorName { get; set; }
        public decimal OriginalCurrencyAmount { get; set; }
        public string Currency { get; set; }
        public decimal ConvertedAmount { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<System.DateTime> DateDeposited { get; set; }
        public string Comments { get; set; }
    }
}
