//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org_maint_services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitySummary
    {
        public int EntitySummaryId { get; set; }
        public long TotalEntities { get; set; }
        public long TotalEntitiesAllocated { get; set; }
        public long TotalEntitiesAllocable { get; set; }
        public long TotalEntitiesUnallocated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
