//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org_maint_services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityItemExpens
    {
        public int EntityItemID { get; set; }
        public int EntityFinanceSummaryID { get; set; }
        public string EntityItemName { get; set; }
        public string EntityItemDetail { get; set; }
        public decimal EntityItemBudgetRequired { get; set; }
        public decimal EntityItemBudgetAllocated { get; set; }
        public short EntityItemPriority { get; set; }
        public Nullable<System.DateTime> EntityItemDateUpdated { get; set; }
        public string EntityItemComments { get; set; }
    }
}
